#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// Get the current directory
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Get the current directory
const projectRoot = path.resolve(__dirname, '../..');
// VS Code extension: read version from the repository package.json.
const pkgPath = path.join(projectRoot, 'package.json');
let version = '0.0.1';
try {
  const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
  if (pkg.version) version = String(pkg.version);
} catch (err) {
  console.warn(`extract-version: falling back to 0.0.1 (${err.message})`);
}
console.log(`Found version: ${version}`);

// Create the version file for the webview
const versionDir = path.join(__dirname, '../src/version');
if (!fs.existsSync(versionDir)) {
  fs.mkdirSync(versionDir, { recursive: true });
}

const versionFilePath = path.join(versionDir, 'version.ts');
const versionFileContent = `// Auto-generated version file
// This file is automatically generated during the build process
// Do not edit manually

export const APP_VERSION = '${version}';
`;

fs.writeFileSync(versionFilePath, versionFileContent);
console.log(`Version file created at: ${versionFilePath}`);
