// Auto-generated changelog file
// This file is automatically generated during the build process from CHANGELOG.md
// Do not edit manually

export interface ChangelogEntry {
  version: string;
  date: string;
  content: {
    en: string;
    zh: string;
  };
}

export const CHANGELOG_DATA: ChangelogEntry[] = [
  {
    version: '0.0.1',
    date: '2026-09-01',
    content: {
      en: `🎉 Initial Release
- OpenCode Buddy: an OpenCode-powered AI coding panel for VS Code.`,
      zh: `🎉 初始发布
- OpenCode Buddy：基于 OpenCode 的 VS Code AI 编程面板。`,
    },
  },
];
